### ISSUE TITLE
[Help]: Windows Defender identifies hellextractor as virus

### ISSUE THREAD

**Issue by daervik** [Xaymar/Hellextractor#13]
Windows Defender identifies hellextractor.exe as Trojan:Win32/Wacatac.B!ml
File: hellextractor.zip->Hellextractor.exe

It would be good to prevent using files or conversions that makes this error happen, as it doesn't make the file seem trustworthy.

**Comment by Xaymar** [comment]
I can't really do anything about heuristic scans, so nothing I can do here.

The code for the tool is in the Code tab, from which GitHub Actions is used to build the binary that ends up on the Releases tab. You can also inspect the script that handles that part in the .github directory of the repository.

**Comment by Xaymar** [comment]
Oh, this isn't even a heuristic scan, it's something even worse: "Artificial Intelligence". That means that the results are basically a probability function where the function is unknown to the observer. Could suddenly stop being marked as such, or it could be marked as something else entirely. Nice.

**Comment by daervik** [comment]
In the previous version, edge blocked the download of the zip due to this issue, so I downloaded with curl through Terminal and scanned with Windows Defender to get the virus warning.

Today I downloaded the zip file of version [v0.6.0a8], edge did not block it and virus scan did not find anything, so looks kinda random yes :/

**Comment by daervik** [comment]
The only "solution" I can think of to compensate for Defender being stupid, would be to do a test download using edge after a new build to see if windows for some reason sees the build as a virus, but yeah, this is just stupid, and looks like no fault of you, so I'm closing this ticket :)
