### ISSUE TITLE
[Help]: Cannot extract files (and cannot run hellextractor.exe)

### ISSUE THREAD

**Issue by 1rone** [Xaymar/Hellextractor#16]
### Describe the Bug

C:\Users\User 1\Hellextractor>hellextractor.exe
'hellextractor.exe' is not recognized as an internal or external command,
operable program or batch file.

Did all Building steps, but receiving this stuff everytime.

And, because of it:

Executing: extract -o ./output "c:\program files (x86)\steam\steamapps\common\Helldivers 2\data"
Start-Process : This command cannot be run due to the error: The system cannot find the file specified.
At C:\Users\User 1\Hellextractor\hellextractor.ps1:113 char:5
+     Start-Process -FilePath "./hellextractor.exe" -ArgumentList $comm ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Start-Process], InvalidOperationException
    + FullyQualifiedErrorId : InvalidOperationException,Microsoft.PowerShell.Commands.StartProcessCommand

**Comment by Xaymar** [comment]
Works just fine here. Make sure that Hellextractor.exe is actually in the place you are running the command from. As for the .ps1/.cmd file, Hellextractor.exe needs to be in the same directory as them.

**Comment by 1rone** [comment]
It looks like hellextractor.exe is not on computer. Here are my directory with project:

![Screenshot 2024-02-29 130859](https://github.com/Xaymar/Hellextractor/assets/57466060/289a7471-bfb9-4af2-b442-c04ed466bd52)

What I did:

1) Git clone
2) cd to project
3) cmake -S. -Bbuild
4) cmake --build build
4.5) PowerShell - as admin, "Set-ExecutionPolicy RemoteSigned"
5) trying to use any commands with hellextractor.exe - there is no such file

**Comment by Xaymar** [comment]
If you build it yourself, Hellextractor.exe will end up in {BUILDDIR}/{CONFIGTYPE}. You need to move it to the directory you want to use it from.

**Comment by 1rone** [comment]
Understood. Found it. Thank you very much!
